package models.Plant;

public enum PlantStatKey {
    DAMAGE, MAX_HP, COST, ACTION_INTERVAL, RECHARGE, PROJECTILE_SPEED,
    RANGE, PIERCE_COUNT, AOE_DAMAGE, CHILL_DURATION, FREEZE_DURATION,
    TARGET_COUNT, LIFESPAN, WARMTH_RADIUS, POISON_DAMAGE, SUN_AMOUNT,
    DOUBLE_SUN_CHANCE
}
