package network.protocol;

public enum MessageType {
    PING,
    PONG,
    REGISTER_REQUEST,
    REGISTER_RESPONSE,
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    LOGOUT_REQUEST,
    LOGOUT_RESPONSE,
    FORGOT_PASSWORD_START_REQUEST,
    FORGOT_PASSWORD_START_RESPONSE,

    FORGOT_PASSWORD_ANSWER_REQUEST,
    FORGOT_PASSWORD_ANSWER_RESPONSE,

    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET_RESPONSE,
    RESUME_SESSION_REQUEST,
    RESUME_SESSION_RESPONSE,

    PROFILE_GET_REQUEST,
    PROFILE_GET_RESPONSE,
    PROFILE_UPDATE_REQUEST,
    PROFILE_UPDATE_RESPONSE,
    PROFILE_PASSWORD_CHANGE_REQUEST,
    PROFILE_PASSWORD_CHANGE_RESPONSE,

    PLANT_OWNERSHIP_GET_REQUEST,
    PLANT_OWNERSHIP_GET_RESPONSE,

    GAMEPLAY_LOOT_COLLECT_REQUEST,
    GAMEPLAY_LOOT_COLLECT_RESPONSE,
    ADVENTURE_LOSS_REQUEST,
    ADVENTURE_LOSS_RESPONSE,
    ADVENTURE_WIN_REQUEST,
    ADVENTURE_WIN_RESPONSE,
    ADVENTURE_PROGRESS_GET_REQUEST,
    ADVENTURE_PROGRESS_GET_RESPONSE,

    GREENHOUSE_GET_REQUEST,
    GREENHOUSE_GET_RESPONSE,
    GREENHOUSE_PLANT_REQUEST,
    GREENHOUSE_PLANT_RESPONSE,
    GREENHOUSE_GROW_REQUEST,
    GREENHOUSE_GROW_RESPONSE,
    GREENHOUSE_COLLECT_REQUEST,
    GREENHOUSE_COLLECT_RESPONSE,

    SHOP_GET_REQUEST,
    SHOP_GET_RESPONSE,
    SHOP_PURCHASE_REQUEST,
    SHOP_PURCHASE_RESPONSE,
    SHOP_DAILY_PURCHASE_REQUEST,
    SHOP_DAILY_PURCHASE_RESPONSE,

    COLLECTION_PLANT_PURCHASE_REQUEST,
    COLLECTION_PLANT_PURCHASE_RESPONSE,
    PLANT_UPGRADE_REQUEST,
    PLANT_UPGRADE_RESPONSE,
    PLANT_BOOST_REQUEST,
    PLANT_BOOST_RESPONSE,
    PLANT_BOOST_CONSUME_REQUEST,
    PLANT_BOOST_CONSUME_RESPONSE,
    PLANT_FOOD_CLAIM_REQUEST,
    PLANT_FOOD_CLAIM_RESPONSE,
    MATCHMAKING_QUEUE_REQUEST,
    MATCHMAKING_QUEUE_RESPONSE,
    MATCHMAKING_QUEUE_LEAVE_REQUEST,
    MATCHMAKING_QUEUE_LEAVE_RESPONSE,

    MATCHMAKING_INVITE_REQUEST,
    MATCHMAKING_INVITE_RESPONSE,
    MATCHMAKING_INVITE_RECEIVED,

    MATCHMAKING_INVITE_DECISION,
    MATCHMAKING_INVITE_DECISION_RESPONSE,
    MATCHMAKING_INVITE_REJECTED,
    MATCHMAKING_MATCH_FOUND,
    MATCH_START,

    MATCH_ACTION_REQUEST,
    MATCH_ACTION_RESPONSE,

    MATCH_SNAPSHOT,
    MATCH_ENDED,

    REACTION_SEND_REQUEST,
    REACTION_SEND_RESPONSE,
    REACTION_RECEIVED,
    ERROR
}
