package network.protocol;

public enum MessageType {
    PING,
    PONG,
    REGISTER_REQUEST,
    REGISTER_RESPONSE,
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    LOGOUT_REQUEST,
    LOGOUT_RESPONSE,
    FORGOT_PASSWORD_START_REQUEST,
    FORGOT_PASSWORD_START_RESPONSE,

    FORGOT_PASSWORD_ANSWER_REQUEST,
    FORGOT_PASSWORD_ANSWER_RESPONSE,

    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET_RESPONSE,
    RESUME_SESSION_REQUEST,
    RESUME_SESSION_RESPONSE,

    PROFILE_GET_REQUEST,
    PROFILE_GET_RESPONSE,
    PROFILE_UPDATE_REQUEST,
    PROFILE_UPDATE_RESPONSE,
    PROFILE_PASSWORD_CHANGE_REQUEST,
    PROFILE_PASSWORD_CHANGE_RESPONSE,

    PLANT_OWNERSHIP_GET_REQUEST,
    PLANT_OWNERSHIP_GET_RESPONSE,

    GAMEPLAY_LOOT_COLLECT_REQUEST,
    GAMEPLAY_LOOT_COLLECT_RESPONSE,
    ADVENTURE_LOSS_REQUEST,
    ADVENTURE_LOSS_RESPONSE,
    ADVENTURE_WIN_REQUEST,
    ADVENTURE_WIN_RESPONSE,
    ADVENTURE_PROGRESS_GET_REQUEST,
    ADVENTURE_PROGRESS_GET_RESPONSE,

    ERROR
}
