package network.protocol;

public enum MessageType {
    PING,
    PONG,
    REGISTER_REQUEST,
    REGISTER_RESPONSE,
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    LOGOUT_REQUEST,
    LOGOUT_RESPONSE,
    FORGOT_PASSWORD_START_REQUEST,
    FORGOT_PASSWORD_START_RESPONSE,

    FORGOT_PASSWORD_ANSWER_REQUEST,
    FORGOT_PASSWORD_ANSWER_RESPONSE,

    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET_RESPONSE,
    RESUME_SESSION_REQUEST,
    RESUME_SESSION_RESPONSE,
    ERROR
}
