package models.Zombie;

public enum ZombieType {
    // All Chapters
    BASIC, CONEHEAD, BUCKETHEAD, BRICKHEAD,
    GARGANTUAR_BASIC, IMP_BASIC, FLAG,

    // Ancient Egypt
    MUMMY, MUMMY_CONEHEAD, MUMMY_BUCKETHEAD, MUMMY_BRICKHEAD,
    PHARAOH, RA, EXPLORER, TOMB_RAISER, CAMEL,
    GARGANTUAR_EGYPT, IMP_EGYPT,

    // Frostbite Caves
    ICEAGE, ICEAGE_CONEHEAD, ICEAGE_BUCKETHEAD, ICEAGE_ICEBLOCK,
    ICEAGE_HUNTER, TROGLOBITE, DODO, WEASEL_HOARDER, WEASEL,
    GARGANTUAR_ICEAGE, IMP_ICEAGE,

    // Big Wave Beach
    BEACH, BEACH_CONEHEAD, BEACH_BUCKETHEAD,
    SNORKEL, SURFER, FISHERMAN, OCTOPUS, FAST_SWIMMER,
    GARGANTUAR_BEACH, IMP_BEACH,

    // Dark Ages
    DARK, DARK_CONEHEAD, DARK_BUCKETHEAD, DARK_SHOULDER_ARMOR, DARK_BRICKHEAD,
    WIZARD, JUGGLER, DARK_KING,
    GARGANTUAR_DARK, IMP_DARK,

    // Bosses
    ZOMBOSS_EGYPT, ZOMBOSS_PIRATE, ZOMBOSS_COWBOY, ZOMBOSS_DARK,
    SUN_PRODUCER_ZOMBIE
}
